### ISSUE TITLE
Implement search across CMS and Docs pages

### ISSUE THREAD

**Issue by nickwynja** [infor-design/website#103]
http://docs.wagtail.io/en/latest/topics/search/index.html

- [ ] Write spec @nickwynja
- [x] Meet with Artem to review details and plan implementation
- [ ] Review with team to kick off designs
- [ ] Wire of what search would look like for Artem to see data structure

**Comment by theakatz** [comment]
@kmahsmith can you design what the search flow could look like for the site? including: search results page and search bar

**Comment by nickwynja** [comment]
@kmahsmith Can you provide more examples?

What happens when:

- [ ] The query doesn't match anything in the typeahead
- [ ] The query matches something in the Guidelines/Examples/Resources pages
- [ ] The query matches something in ALL categories

I'm sure there will be more cases too..

**Comment by kmahsmith** [comment]
Yep, updated the flow a bit

![blank diagram - page 1 1](https://user-images.githubusercontent.com/34688242/40198272-ec9e6b3c-59e3-11e8-9b48-5eedf8d609a4.jpeg)

- The query doesn't match anything in the typeahead = "No Results"
![no item search](https://user-images.githubusercontent.com/34688242/40198285-fe11cc6a-59e3-11e8-88ae-da053aa687fb.jpg)

- The query matches something in the Guidelines/Examples/Resources pages = Display categories. If duplicates in code display Enterprise Components 
- The query matches something in ALL categories
![category search](https://user-images.githubusercontent.com/34688242/40198311-199b6e32-59e4-11e8-9e34-4203b10c367e.jpg)

**Comment by nickwynja** [comment]
We won't be able to get this done for this major May release. There's a chance we could get something patched in early in June but I think we have to "Go Public" with the site how it is.

**Comment by kmahsmith** [comment]
update specs see https://paper.dropbox.com/doc/Q1FY19-Planning-1PTJWJo1YscVx8aVOOop9#:uid=444321462082588042219835&h2=Design/Features-MVP
