### ISSUE TITLE
Blog Landing and Content Page Design with Source Sans

### ISSUE THREAD

**Issue by theakatz** [infor-design/website#336]
- [x] Kayiu to design landing page for where the blog will live
 ---using source sans font and utilizing the layouts that Noah and Danielle started with 

Blog to hold both time content vs evergreen content 
Will hold release notes and in progress and evergreen content that Kayiu and Kelsey would work on 

Requirements that were for comms team and left just in case for notes:

- author/date
- should have same global navigation as design system (top nav) 
- template should allow for images of different sizes and alignments
- use existing typography h1-p 
- use draft vertical rhythm 
- need a mi-fi mockup 
- responsive

**Comment by kayiuho** [comment]
![ids_blog_landing_v1](https://user-images.githubusercontent.com/34747859/38952273-08243e86-4319-11e8-8d5a-a328095a6a73.jpg)

What do we think of this simple layout to start with?

Thoughts on having a quick newsletter sign up on the bottom of the page? We can also capture other data like products, roles, maybe even non-Infor people.. Any implementation concerns? Or should we just have a link that sends people to fill out the sign up form on mailchimp?

**Comment by Whatsupnoah4635** [comment]
Looks fine; I like the idea of a quick newsletter signup at the bottom…

**Comment by kmahsmith** [comment]
Looks good. Whats the character count per line? I think the optimal reading length is 45-75. We might need to go down a column or two.

**Comment by kayiuho** [comment]
Oh, yikes! Overlooked there. It's about 150 right now. Let me bring that in some more.

**Comment by kayiuho** [comment]
![ids_blog_landing_v2](https://user-images.githubusercontent.com/34747859/39010101-9b16fbf8-43db-11e8-9402-1bd440194795.jpg)

@jmacaluso711  - here's the updated blog page w/ design annotation. I tried using design tokens to reference as much as possible. Let me know if that's helpful?? Let me know if there's anything I'm missing, I'll attach the other screen sizes shortly!

**Comment by clepore** [comment]
We have a mailchimp login for hook and loop but we also have one separately for other stuff. I"ll get those figured out and invite you guys. Give me a day or so.

**Comment by jmacaluso711** [comment]
Great thanks...Just a couple questions

For tags, if we use them, are they going to click through to a tag archive page or are they just for display?

Is the author a field that will be filled in or is it based on the person that wrote and/or enters in the article in the backend. Or will it always be "The Infor Design System Team"?

**Comment by kayiuho** [comment]
Good questions. For author, It'll most likely be the IDS team (to start with) but not always? I am thinking any one of us can be the author if there's specific topics we want to post about. 

I think if we don't have categories then tags would be good.. we obviously don't have much content to filter thru right now, so it could be an add on for later. (If we do post tags, we'll just add a line on the top of the 1st post, something like "_Posts in: Release Note_", which I can mock up real quick..)

**Comment by nickwynja** [comment]
Usually the additional form fields for a mailchimp list signup happen on the mailchimp site as part of their "double confirm" process, so we'd only need the email field on our site.

**Comment by kayiuho** [comment]
Right.. In the past I've embedded codes (copied from mailchimp) to a website before with just collecting the email address as input. We certainly can just do that for the blog footer. 

If we want to embed the form (with more than just email address), there's an option to do that ([](https://kb.mailchimp.com/lists/signup-forms/add-a-signup-form-to-your-website)). If we want to collect names along with email addresses, we can use the Classic embed form. Then in the Thank You/Welcome e-mail, it can be more personalized with the collected name. I think we can do custom css with the Classic embed form.

There's the regular signup form that's hosted on the mailchimp side (I think that's what you were talking about), it has a custom URL that we can send/link people to, and we can also collect better data when people sign up.

Which option are we thinking of going with? I don't see an option with both embed form (collects email) then send you to the mailchimp page to fill out other stuff.

I don't have access to the Form Builder (under Lists) on mailchimp but I do have a personal account that I've been poking around with.

Sorry for the long message!

**Comment by kayiuho** [comment]
@jmacaluso711 It's now in the difference breakpoints. I shared the Sketch file via my OneDrive folder, let me know if you can't download it. I can also slack the file but thought we should keep records all together here.

File link:
https://inforonline-my.sharepoint.com/:u:/r/personal/kayiu_ho_infor_com/Documents/Kayiu-work-in-progress/SoHo_IDS/_System/Blog/IDS_site_blog.sketch?csf=1&e=utTMGD

**Comment by clepore** [comment]
@kayiuho I made you a manager, so try the form stuff now?

**Comment by kayiuho** [comment]
@jmacaluso711 can we make these changes below?

.blog .page-content {
    border-top: 8px solid #fbe9bf;

.blog-post--header {
    margin-bottom: 32px;

.blog-post--title {
    margin-top: 12px;
    margin-bottom: 12px;

.newsletter-signup--form-container {
    margin-top: 32px;

.ids-row, .ids-row--gutter {
    margin-bottom: 12px;

Seems like the line-height isn't defined for H1? It should be 1.6 (64px).

For the MC form, if a user enters name and email w/o errors, it'll just submit the form. It will only take you to the full form when there's an error. Is there something we can do to take users to the form either way?

**Comment by nickwynja** [comment]
Looks like we can do this: https://blog.mailchimp.com/how-to-pre-fill-items-on-your-mailchimp-hosted-form/

```
https://infor.us18.list-manage.com/subscribe?u=50922b2a4dbfe95c954a9ebd6&id=6ed131db92&MERGE0=nick.wynja@infor.com
```

**Comment by kmahsmith** [comment]
@kayiuho and @jmacaluso711 Hey, sorry chiming in late here. A couple of thoughts on the landing page

- I wonder if we need the yellow bar up top. I think its the placement thats throwing me off. Since its full width under the header it feels more like an alert banner as opposed to just a visual design element.

- Blog post truncation. Looks like the entire blog is posted on the landing page with the h1 being a link. I wonder if we should truncate the body content to like 170 characters (about a line and half). We might have really long blog posts as the content expands and having the entire article would increase scroll time.

- The newsletter callout on the bottom feels maybe a bit too large. The type hierarchy feels like its competing with the content above it, as opposed to being secondary content. 

what if we..
- [ ] use h2 bold and p fonts
since the body above is 5 cols, and the NL is left aligned at 7 body col there is a bit of a jump when reading left to right
![screen shot 2018-05-03 at 2 32 53 pm](https://user-images.githubusercontent.com/34688242/39596056-410f7cc0-4edf-11e8-9294-4933acc6042c.png)
- [ ] center align items in div to max width of the body above
- [ ] flex input form and buttons on one line 
- [ ] make input forms smaller
- [ ] make input background white
- [ ] update copy on button to be "Subscribe" feels more explicit
- [ ] maybe a different color? the yellow feels like a status color 

![screen shot 2018-05-03 at 2 29 44 pm](https://user-images.githubusercontent.com/34688242/39595844-9d0930d0-4ede-11e8-972e-d8b0dd1c3804.png)

**Comment by clepore** [comment]
@kmahsmith we can keep the conversation going here, but lets move any actionable items to a new ticket (since its technically updates to what we already built and released)...i.e: `"Update Blog Landing/Content Page"` or something like that and just link it here.

**Comment by nickwynja** [comment]
We can address these changes in #537.
