### ISSUE TITLE
A/B Testing of Site

### ISSUE THREAD

**Issue by theakatz** [infor-design/website#426]
Testing to begin after 4/2

- [x] Kelsey to provide Evan prototype by EOW (add to this ticket) 
- [x] Evan to A/B test the navigational hierarchy 

Timing: Need testing complete by EOMarch, May release we want updates from testing complete

Notes: 
Need in current build
Fixed/Active state of top nav
2 column layout types

**Comment by ecaminiti** [comment]
[IDSResearchCaseStudyApril2018.pdf](https://github.com/infor-design/website/files/1972161/IDSResearchCaseStudyApril2018.pdf)

You can view the case study of this testing effort here ^
