### ISSUE TITLE
Create Card Layouts

### ISSUE THREAD

**Issue by kmahsmith** [infor-design/website#470]
Grid layout for "Types" on Elements and Blocks

# Rules:
- when one image - float left align. 
- when two images - flex left to right
- when over two images - flex left to right and down

# Adaptive Design
- we need to manage two layouts in order to get the alignment right on different breakpoints.

## XL-L 
- layout should horizontally align items so h2s per 3 col div, p div, and img div.
![artboard copy 10](https://user-images.githubusercontent.com/34688242/38110952-49de2188-336b-11e8-930d-be72bd4ce16e.jpg)
- use existing margins assigned to h2, p, and img

## M-XS
- layout should vertically align. So div will now contain h2, p, and image / 
![artboard copy 9](https://user-images.githubusercontent.com/34688242/38111124-cdf46e82-336b-11e8-9646-31c459337727.jpg)

-----

# Not in scope for first pass
Card layout to go on guidelines, examples, resource and landing pages.

## CMS Slots (times 2)
- h2 or h3. option to have either or. 
   - If h2 slot is empty, h3 is primary. If h2 and h3 filled in then formats with h2 on top of h3
- p
- image
![artboard5](https://user-images.githubusercontent.com/34688242/38111318-7fb28dfc-336c-11e8-9d55-d0a652ca2d01.jpg)

## CMS Styling Options
- display image top (above h2/3 and p)
- display image bottom (below h2/3 and p)
- align div - center, left, right

![artboard](https://user-images.githubusercontent.com/34688242/38110546-0517c302-336a-11e8-908c-29fba4fabe81.jpg)

**Comment by jmacaluso711** [comment]
so is this a "Card" streamfield that will be added to corecontent, element and blocks page types?

**Comment by kmahsmith** [comment]
yes

**Comment by nickwynja** [comment]
Got to correct Kelsey here: this will just be an update to the front-end rendering of the `types` data coming from the elements and blocks.
