### ISSUE TITLE
"Select All" image has an extra line

### ISSUE THREAD

**Issue by clepore** [infor-design/website#473]
Per @tmcconechy :
> Minor issue on https://design.infor.com/guidelines/components/elements/checkbox
> One the drawings  has an extra line:
![screen_shot_2018-03-30_at_7 26 33_am](https://user-images.githubusercontent.com/742319/38139789-ec6ab4fa-33fe-11e8-844e-330ca78f0129.png)

**Comment by nickwynja** [comment]
Maybe "Item One" here should read "Select All"?

**Comment by tmcconechy** [comment]
Ah that would make sense as well..We have this on multiselect/popupmenus and possibly on forms (but dont have an example)

**Comment by kayiuho** [comment]
Oh, yup. That should be a "Select All" not "Item One".

**Comment by nickwynja** [comment]
@kayiuho Can you close this ticket when you've updated the image?
