### ISSUE TITLE
Sidebar design hierarchy "headings" too sublte

### ISSUE THREAD

**Issue by clepore** [infor-design/website#500]
The current nav bar on the website has small indentations and the carets are so far away from the "headings" that its tough to get a sense of the over all hierarchy.

### Some options:
- Make headings more bold
- increase indentation
- change font size (might help to make the list smaller in general)

### Examples:
- Increase indentation (increments of 8):
    <img width="184" alt="increse-indentation" src="https://user-images.githubusercontent.com/742319/38517658-a95a6202-3c08-11e8-8dbc-65e56b68ec43.png">

- Maybe add light borders:
    <img width="239" alt="borders" src="https://user-images.githubusercontent.com/742319/38517668-ae5fc774-3c08-11e8-8104-725d9bc0921c.png">

**Comment by theakatz** [comment]
IDS team wants BOTH PLEASE
