### ISSUE TITLE
IDS Newsletter Subscribe

### ISSUE THREAD

**Issue by theakatz** [infor-design/website#508]
**Needs before 5/10** 
- [x] Mailchimp template to be designed for 'thank you for subscribing email'
- [x] Design for a push to sign up on site--likely one in footer and perhaps one additional place (maybe home) if we want to plug it more when we first announce IDS release 
- [ ] kayiu to mock up in line on the landing pages and full width on the home page
- [ ] Implementation of plug to sign up onto site by John 

**Can have after 5/10**
- [ ] Mailchimp template to be built for newsletter content

**Comment by clepore** [comment]
@kayiuho Just let us know when the designs are done and attach them here and we'll figure out the dev work 👍

**Comment by kayiuho** [comment]
Do we see a need for a global footer so we can house a little thing about newsletter sign up, a github mark, and maybe a latest version number and date? or should we not do that for now but later?

Example:
<img width="1151" alt="screen shot 2018-04-19 at 4 27 24 pm" src="https://user-images.githubusercontent.com/34747859/39016586-dfed387e-43ee-11e8-86c3-93babb5532eb.png">

**Comment by kayiuho** [comment]
Or we can find a place on the bottom of the HP, maybe share that space next to the faq's section?

**Comment by theakatz** [comment]
Nick did mention having it live in a footer, so it might make sense to have one if we have other things that would go down there

**Comment by kayiuho** [comment]
add Terms & Conditions link on footer.

**Comment by kayiuho** [comment]
Posting these mocks here for possible options.. Thoughts? @kmahsmith @jmacaluso711 

<img width="1439" alt="screen shot 2018-05-13 at 9 52 14 pm" src="https://user-images.githubusercontent.com/34747859/39974657-265c5788-56f8-11e8-8493-687b49a8ff2f.png">

<img width="1440" alt="screen shot 2018-05-13 at 9 51 47 pm" src="https://user-images.githubusercontent.com/34747859/39974662-2a2b72d6-56f8-11e8-91da-4b6492a68134.png">

Also, what if we do an additional modal push on the Blog page for newsletter sign up (once you've reached the bottom of the page). @jmacaluso711 Would that be hard to do?

**Comment by theakatz** [comment]
@kayiuho can you please attach the mailchimp thank you design and attach for John to take a look por favor

**Comment by kmahsmith** [comment]
@kayiuho looks good!  I think some of the alignment feels a bit off because the body can be both centered and left aligned. Also, what would happen to this design on medium?

What if we tried stacking is so the index links are on top flex left to right with the email centered below? 

I think if we visually separate it more from the formatting for the body, it can serve more as an anchor weight.

**Comment by kayiuho** [comment]
@jmacaluso711 The MailChimp thank you page template is already made under their Form Builder "Confirmation Thank You Page". Is this what you're looking for?

![screen shot 2018-05-15 at 12 04 26 pm](https://user-images.githubusercontent.com/34747859/40069133-758d7b5c-5838-11e8-8147-22c0f2f9f7bc.png)

**Comment by kayiuho** [comment]
Like the actual email/newsletter that people will get? Those are designed and managed within "Campaigns" and I don't think there's anything that would need to get implemented..

**Comment by kmahsmith** [comment]
Looks good? Maybe we can make the headline a size smaller though?

**Comment by kayiuho** [comment]
Can't attach Sketch file here but you can download the file via OneDrive: https://inforonline-my.sharepoint.com/:u:/r/personal/kayiu_ho_infor_com/Documents/Kayiu-work-in-progress/SoHo_IDS/_Main/IDS_Site/Footer/IDS_site_footer.sketch?csf=1&e=r8bd9k

**Comment by clepore** [comment]
@jmacaluso711 here it is as a .zip 😝 haha!

[IDS_site_footer.sketch.zip](https://github.com/infor-design/website/files/2010393/IDS_site_footer.sketch.zip)

**Comment by kayiuho** [comment]
I tried :/ 
<img width="677" alt="screen shot 2018-05-16 at 2 36 35 pm" src="https://user-images.githubusercontent.com/34747859/40136737-9258299c-5916-11e8-87c7-6b3e65b2da0a.png">

OneDrive is dumb but sending files via Slack gets lost. I'd rather have the record of it all here instead of multiple places.

**Comment by clepore** [comment]
My solution was to zip it, then github doesn't care :) lol
