### ISSUE TITLE
Blurb to Explain What Happened to Soho 

### ISSUE THREAD

**Issue by theakatz** [infor-design/website#509]
Need something on home page to explain what happened to soho. This is for people who come to the site thinking they are about to land on the soho site.

- [x] Julie to write blurb explaining
- [x] Might need some design in terms of layout on home page ? 
- [ ] Chris/John to implement onto home page

**Comment by theakatz** [comment]
related to https://github.com/infor-design/website/issues/561

**Comment by JulieAnnBriggs** [comment]
**What Happened to SoHo?**
Don’t worry. Your work hasn’t gone anywhere, and the new Infor Design System does not replace the 4.x controls which will continue to be updated. Instead, we have added improved guidelines and documentation to guide component use. We are still supporting SoHo tickets but eventually, we will archive the current SoHo site and redirect many resources here.

**Comment by theakatz** [comment]
Thanks for your help Julie! 

Tweaked blurb here: 
**What Happened to SoHo?**
Don't worry. We are not deprecating the 4.x controls. Instead, we have defined a system of improved guidelines and documentation for the usage of the Enterprise controls (soho controls) called the Infor Design System, aka IDS. You will now be able to find everything you were looking for on soho.infor.com (and more) right here.

@kayiuho onto you for design when you are free! Then John will implement.

**Comment by JulieAnnBriggs** [comment]
Cool. I took your changes and lightly copyedited just for correct capitalization/punctuation. 



**What Happened to SoHo?**
Don't worry. We're not deprecating the 4.x controls. Instead, we have defined a system of improved guidelines and documentation for the usage of the Enterprise controls (SoHo controls) called the Infor Design System, A.K.A IDS. Now, you can find everything you were looking for on soho.infor.com (and more) right here.

**Comment by kayiuho** [comment]
Thanks @JulieAnnBriggs! 

I'll get the design over to you @jmacaluso711 when I have a moment.

**Comment by kayiuho** [comment]
@jmacaluso711 working on this and will have the design over to you tomorrow!

**Comment by kayiuho** [comment]
@jmacaluso711 This is mocked up. Wanna get feedback from the team.. 

![screen shot 2018-07-17 at 10 17 58 am](https://user-images.githubusercontent.com/34747859/42823112-bbea8948-89aa-11e8-9ac5-f13291a95fad.png)

**Comment by theakatz** [comment]
Looks good. All for you @jmacaluso711 to implement please! We want this modal to only show up when the user is redirected from soho.infor.com

**Comment by jmacaluso711** [comment]
Does it appear only the first time someone is redirected or everytime?

**Comment by theakatz** [comment]
Do every time... because if they keep trying to go to soho then they probably reallyyy want it and need to read our blurb even more than the average person.
