### ISSUE TITLE
Bug: Typo Code > CSS Library 

### ISSUE THREAD

**Issue by kmahsmith** [infor-design/website#513]
Rick caught this type on the CSS library getting started page 
![screen shot 2018-04-23 at 4 48 22 pm](https://user-images.githubusercontent.com/34688242/39152405-47b6acae-4716-11e8-9dae-6e3ec8f42f9e.png)

Can't edit via cms

**Comment by nickwynja** [comment]
A fix for this will go out in the next release of the CSS library.
