### ISSUE TITLE
Change Top Nav Color 

### ISSUE THREAD

**Issue by kmahsmith** [infor-design/website#519]
The current top nav is white and doesn't have enough hierarchy from the the body and side panel.

Lets update to be
- [ ] background: Page Level Bar - Slate 7 #414247
- [ ]  font color: white - might need to adjust the opacity, because the font goes to full white on hover
- [ ] carrot color white
- [ ] clicked underline state white

I also wanna make the top nav smaller too
- [ ] padding top padding bottom 8px
- [ ] category font size: 14px
- [ ] design system font size: 16px

<img width="1393" alt="screen shot 2018-04-26 at 4 08 00 pm" src="https://user-images.githubusercontent.com/34688242/39329359-130e58a0-496c-11e8-9f5d-d8548b4a5aca.png">

also works on responsive too
<img width="399" alt="screen shot 2018-04-26 at 4 08 16 pm" src="https://user-images.githubusercontent.com/34688242/39329364-1665c02e-496c-11e8-822c-dd776e8e9f2b.png">

**Comment by nickwynja** [comment]
Sorry to always be the fun ruin-er...

This directly competes with the visual style of the Ming.le shell

![image](https://user-images.githubusercontent.com/1012017/39379339-e617486c-4a28-11e8-9c98-ba0c16c22074.png)

It's so close, even with the Infor logo and product name alignment that I think we'd be misleading people with our "mingle shell but not mingle shell" header.

**Comment by kmahsmith** [comment]
true, but technically this is style that we recommend in soho.

![light ui color scheme](https://user-images.githubusercontent.com/34688242/39379509-75b4ba68-4a29-11e8-81e6-8d1a20eb5716.jpg)

**Comment by kmahsmith** [comment]
i guess the other option would be to make the header blue, and change the menu button to default

**Comment by kmahsmith** [comment]
We're not making any new style decisions. We're simply using the UI as already defined by Soho. This is a standalone site, I don't think it will be confusing with the mingle shell. We're using our recommendations to demonstrate visual hierarchy.

**Comment by tmcconechy** [comment]
Having some history i kind of agree with Nick. Someone will probably ask if the mingle shell should be updated / and or why the components don't match. Mainly because its so close (and actually looks like an improvement)

**Comment by kmahsmith** [comment]
But in soho page level headers can have this color value, and so can the mingle shell.

**Comment by tmcconechy** [comment]
OK, i guess thats true for the header as it can be customized. But for the shell there wasn't any customization options. This looks very similar so threw me off. 

I guess if its a header not the mingle shell its not anything new, then.

**Comment by kmahsmith** [comment]
closing this ticket. we're going to leave white.
