### ISSUE TITLE
Top Nav Button Active State

### ISSUE THREAD

**Issue by kmahsmith** [infor-design/website#524]
Currently the active state of top nav buttons have the underline which is really the width of the button border. Can we update so the active state is the hover color 1a1a1a.

I think the big underline feels quite bulky, especially if we make the top nav shorter in height 

![screen shot 2018-04-30 at 3 12 54 pm](https://user-images.githubusercontent.com/34688242/39445442-0bbd47e4-4c89-11e8-8c3d-35a2beaca6b5.png)

**Comment by theakatz** [comment]
Nick/Kelsey to connect

**Comment by kmahsmith** [comment]
@nickwynja let me know when you wanna chat about this

**Comment by kmahsmith** [comment]
ok, i mean i get it. I'll close because its not worth the level of effort
