### ISSUE TITLE
Top Nav Updates

### ISSUE THREAD

**Issue by kmahsmith** [infor-design/website#525]
- [ ] remove box shadow on top nav. replace with border bottom 1px solid #999999
- [x] update padding top and bottom to be 8px instead of 16px
- [ ] update top nav categories to be 14px instead of 16px
- [x] update infor logo to be height of 34px instead of 40px

![screen shot 2018-04-30 at 4 14 16 pm](https://user-images.githubusercontent.com/34688242/39448003-94453ce0-4c91-11e8-84bb-4a1043c6e16e.png)

**Comment by theakatz** [comment]
Nick and Kelsey to connect on this request...

**Comment by nickwynja** [comment]
@kmahsmith I got some of these tweaks (and active state adjustments from #524) on staging. 

Please check it out at https://staging.design.infor.com/guidelines and let me know what think.

I left the box shadow because it just seemed too dull without it.
