### ISSUE TITLE
Side Panel Updates

### ISSUE THREAD

**Issue by kmahsmith** [infor-design/website#526]
Currently the custom scroll bar on the side panel and body just has left and right borders. 
- [x] add background color f0f0f0 
- [x] on Components/Code section add 24px padding between form groups and index list on the side panel

![screen shot 2018-04-30 at 4 15 52 pm](https://user-images.githubusercontent.com/34688242/39448070-c7adcf2a-4c91-11e8-8a27-06be36be7b61.png)

**Comment by jmacaluso711** [comment]
closed by #543

**Comment by jmacaluso711** [comment]
closed by #543
