### ISSUE TITLE
Add banner to soho.infor.com asking user to opt in to visiting design.infor.com instead

### ISSUE THREAD

**Issue by theakatz** [infor-design/website#527]
- [x] design needed for banner
- [ ] banner implemented onto soho.infor.com 
- [ ] rick to implement tracking on banner so we can see percentage of people opting in to visiting the new site instead

**Comment by tmcconechy** [comment]
So its just some sort of a banner they can click? Or do we want a full redirect? Once you have the design i can quickly add it.

Let me know what i need to do for tracking Rick...

**Comment by theakatz** [comment]
Just a banner for now. We will do a full redirect at a later date. We have a separate ticket for that.

**Comment by tmcconechy** [comment]
Should this go on every page or just home?

**Comment by kayiuho** [comment]
Let me find out and get back to you..

**Comment by kayiuho** [comment]
Hi @tmcconechy - we're going to do a modal instead of a banner for now (only show once on HP). 

Here's the design with "in-line" spacing specs. Message title: 18px; body: 14px. 

Let me know if that's helpful or if it needs to be spec-ed differently. Thanks!

<img width="1437" alt="screen shot 2018-05-09 at 2 53 56 pm" src="https://user-images.githubusercontent.com/34747859/39834008-b619676a-5399-11e8-987c-205c7ad45a87.png">

**Comment by theakatz** [comment]
@swetteinfor when URL is ready please post it in here for Tim to add to banner

**Comment by theakatz** [comment]
I would say to wait, since I think it would be good to track and we haven't made the big announcement yet, so it's ok to wait.

**Comment by theakatz** [comment]
We're starting to announce this more and more, so would be good to get the banner up. 

@swetteinfor can you please add the trackable link here so Tim can deploy?

**Comment by swetteinfor** [comment]
ok. so because we have the old soho and IDS in the same analytics property, a campaign utm link is a no-no because it triggers a "new session" which technically we do not want and will cause confusion. instead, we need to do what is called an "internal campaign." I can add instructions in the next comment.

**Comment by swetteinfor** [comment]
here are the instructions, there are 3 pieces to it.

just a caution,  if a user clicked on the link and by accident sees the modal a second time, we don't want to update the custom dimension to dismiss. if we dont think we can reliably avoid them seeing it a second time, we can just not add the custom dimension entirely. 

when the pop shows to the user, this line of code should run:
 ga('send', 'event', ‘internalcampaign', ‘view', ’SohoIDSAnnouncement’ );

if the user clicks the ok button, run this:
 ga('send', 'event', ‘internalcampaign', ‘click', ’SohoIDSAnnouncement’ , { dimension1’, ‘clickedIDSannouncement' } );

if they do not proceed run this code:
ga('send', 'event', ‘internalcampaign', ‘dismiss', ’SohoIDSAnnouncement’,  { dimension1’, ‘dismissedIDSannouncement' });

**Comment by tmcconechy** [comment]
So do we think we should only ever show the model once when they go to soho.infor.com ? Was thinking I’d just show it every time?

**Comment by theakatz** [comment]
I agree with Rick. I think we should only show once. If they dismiss then they dismiss because they want to stay on soho. It will be crazy bothersome for them to continuously hit cancel every time they come to soho and we don't want their first experience with the design system to be negative because they were annoyed by a banner that was promoting it...

**Comment by tmcconechy** [comment]
Changed those to:
```
ga('send', 'event', 'internalcampaign', 'view', 'SohoIDSAnnouncement' );
ga('send', 'event', 'internalcampaign', 'dismiss', 'SohoIDSAnnouncement', { 'dimension1': 'dismissedIDSannouncement'});
ga('send', 'event', 'internalcampaign', 'click', 'SohoIDSAnnouncement' , {' dimension1': 'clickedIDSannouncement'} );
```

Also what code do i need to make those `ga` objects exist?

**Comment by swetteinfor** [comment]
per theas last comment, i wasn't raising a new interaction point, i was merely pointing out that if we use the dimension value, that we should only record that dimension with a one way directionality. basically they can only switch from "dismissed" to "take me there"

**Comment by tmcconechy** [comment]
OK done. I activated the banner on https://soho.infor.com/ it will just show once.
And will log as setup by Rick

**Comment by theakatz** [comment]
Looks great!! Nice work team!
