### ISSUE TITLE
Research: Component Categories 

### ISSUE THREAD

**Issue by kmahsmith** [infor-design/website#539]
Right now on the site, we separate components into Elements and Blocks. It's apart of the site architecture and the way we talk about assembling items on a page.

We should do research to see if this actually sticks with our users. Do they care, does it make sense?

**Comment by theakatz** [comment]
@ecaminiti please take a look. I will set up time for us to discuss

**Comment by theakatz** [comment]
hey @ecaminiti kayiu will follow up with you on this this week

**Comment by kayiuho** [comment]
hey @ecaminiti, sorry for the delay - I got put on another project.

We wanted to test and see if our users care about the components being in two separate "buckets" (Elements and Blocks) which then could inform us how to enhance our educational material on the site. 

Any thoughts on how to proceed with this user test?
