### ISSUE TITLE
Resources Landing Page Cards

### ISSUE THREAD

**Issue by kmahsmith** [infor-design/website#551]
see also #470 

On Design index pages we added in tows for XL-M and Cards on S-XS. So the copy and images would be horizontally aligned and then stack to cards.

![screen shot 2018-05-22 at 11 57 03 am](https://user-images.githubusercontent.com/34688242/40374598-62a510e8-5db7-11e8-8fb1-3aa5ae5b4eae.png)

Can we also add this format to resources. It looks like they were created as cards on XL-XS, so the copy and buttons don't horizontally align

 https://design.infor.com/resources
![screen shot 2018-05-22 at 12 04 15 pm](https://user-images.githubusercontent.com/34688242/40374959-48e8d3dc-5db8-11e8-8871-2b742c19e3c7.png)

=

**Comment by nickwynja** [comment]
Unassigning until this can be reviewed in grooming and planning.
