### ISSUE TITLE
Identify team UserIDs and remove our cookies from site tracking information

### ISSUE THREAD

**Issue by theakatz** [infor-design/website#553]
Want to make sure when we are on site analytics isn't tracking our time spent there. @swetteinfor  should be able to filter some of the information out that is from testing/team members.

**Comment by swetteinfor** [comment]
I am waiting on storing the userId in the google user_id field as well as our own custom dimension. https://github.com/infor-design/website/issues/564. once we do this we can create a segment and a view that ignores those user ids. We will have to keep a list of the userids handy somewhere so we can add to the list.

**Comment by theakatz** [comment]
dependent on #564

**Comment by theakatz** [comment]
how we doing on this task?

**Comment by theakatz** [comment]
this done yet?

**Comment by clepore** [comment]
Rick said he's pretty busy so we'll let this fall out and bring it back in when he has time.

**Comment by theakatz** [comment]
bringing this back in the sprint! Let me know if you have any questions! @swetteinfor

**Comment by theakatz** [comment]
@swetteinfor can you complete by EOW?
