### ISSUE TITLE
In Line: 'Was this Helpful?' on content pages

### ISSUE THREAD

**Issue by theakatz** [infor-design/website#554]
- [x] Need a design for in line--was this helpful yes or no 
      - add option for open field to comment
      -where would this content go for us to be able to review it? @swetteinfor 

- [ ] Rick to add any tracking that is needed to this
- [ ] John to implement this onto site 
      -This should live: on all internal content pages, but not on the landing pages
      -potentially will live at the bottom of the page, but should play around with placement

**Comment by kayiuho** [comment]
Design options:
- container (1px border)
- divider (1px rule)
- icons (thumb up and down)
- default (grey) buttons for Yes and No
- "Thanks for your feedback!" after rating
- bottom of the page/end of article

**Later on, we can collect open-ended feedback via a comment box, if user answers with No. 

What are our thoughts? @kmahsmith @theakatz @jmacaluso711 

<img width="1433" alt="screen shot 2018-05-29 at 3 30 11 pm" src="https://user-images.githubusercontent.com/34747859/40681553-752f57b4-6357-11e8-936a-90fdbd6632fe.png">

<img width="1435" alt="screen shot 2018-05-29 at 3 30 30 pm" src="https://user-images.githubusercontent.com/34747859/40681555-7853450e-6357-11e8-86fe-0ec5abe1b2d5.png">

<img width="1434" alt="screen shot 2018-05-29 at 3 30 43 pm" src="https://user-images.githubusercontent.com/34747859/40681560-7b23e928-6357-11e8-8f4f-15862586caf1.png">

<img width="1435" alt="screen shot 2018-05-29 at 3 39 00 pm" src="https://user-images.githubusercontent.com/34747859/40681566-7d86dfcc-6357-11e8-8d7f-542021a9cebc.png">

<img width="1433" alt="screen shot 2018-05-29 at 3 37 13 pm" src="https://user-images.githubusercontent.com/34747859/40681572-7f4a0744-6357-11e8-99ee-c056cc8cb38a.png">

**Comment by kmahsmith** [comment]
looking good. Are the thumbs up/down apart of our icon library?

**Comment by kayiuho** [comment]
They are in the Enterprise library (but not the css library).

**Comment by kmahsmith** [comment]
ok, ya i'm leaning towards the icon one. the two buttons feel a bit heavy. For the icons though, what if they were both gray instead of the thumbs up being green. Don't want to influence decisions by favoring one icon over the other.

**Comment by kmahsmith** [comment]
we could also try radio buttons too if the icons still don't feel right

**Comment by kayiuho** [comment]
Oh, the green one is supposed to be an active state (red for thumbs down). They're both default grey in normal state. 

What about the border vs. divider? I think the divider might be better if we will add a comment box later on, then it won't be a box inside a box sort of thing.

**Comment by kmahsmith** [comment]
Ah ok got it! Ya, I think the border feels better and good call once we add in a input field later on.

**Comment by kayiuho** [comment]
Updated mocks with comment box, which will be triggered once users click on the thumbs up/down icon:

![screen shot 2018-05-30 at 12 13 01 pm](https://user-images.githubusercontent.com/34747859/40733234-2412cbd4-6403-11e8-93fc-9077d73a4088.png)

![screen shot 2018-05-30 at 12 13 21 pm](https://user-images.githubusercontent.com/34747859/40733241-271d9dfe-6403-11e8-9862-58061da665ef.png)

![screen shot 2018-05-30 at 12 13 30 pm](https://user-images.githubusercontent.com/34747859/40733257-2cb5fb44-6403-11e8-9133-1de112154e91.png)

![screen shot 2018-05-30 at 12 13 38 pm](https://user-images.githubusercontent.com/34747859/40733265-308df05a-6403-11e8-96d4-c6553d696a28.png)

Let me know if there's any more thoughts before @jmacaluso711 starts working on it??

**Comment by kmahsmith** [comment]
nice! small suggestion. maybe instead of "Input text" it could read "Type comment here" something a little more explicit. 

Also depending on what the character limit is, we might need to make the input field bigger or smaller to demonstrate the affordance.

**Comment by kayiuho** [comment]
We can def change the "hint text" - "Input text" is just the default from the Kit.

In terms of character limit, @swetteinfor what's the max that GA allows? And @jmacaluso711 for input fields, can we add something like "300 characters remaining" under the box? or does the default input token already comes with that by default?

**Comment by jmacaluso711** [comment]
@kayiuho would have to add the character countdown. Should be pretty simple.

**Comment by swetteinfor** [comment]
The character limit is around 2k, lets assume we'll be good with a 1500 character count. I will test this on my end. I assume Jmac can update the max character count if we need to.

**Comment by kayiuho** [comment]
Sweet. I'll update a couple things on the design mock and attach the Sketch file in a Zip here.

**Comment by kayiuho** [comment]
@jmacaluso711 Sketch is here:
[IDS_site_feedback.sketch.zip](https://github.com/infor-design/website/files/2058679/IDS_site_feedback.sketch.zip)

**Comment by swetteinfor** [comment]
FOR JMACS EYES ONLY

  User: sees feedback widget and hovers on it, then clicks up or down
  Category: feedback
  Action: uniquehover, clickthumbsup, clickthumbsdown
  Label: wasthishelpful


  ga(‘send’, ‘event’, ‘feedback’, ‘uniquehover’, ‘wasthishelpful’ );
  ga(‘send’, ‘event’, ‘feedback’, ‘clickthumbsup’, ‘wasthishelpful’ );
  ga(‘send’, ‘event’, ‘feedback’, ‘clickthumbsdown’, ‘wasthishelpful’ );


  User: after clicking the feedback, user gives free text
  Category: feedback
  Action: providedfeedback-thumbsup, providedfeedback-thumbsdown
  Label: [feedback text]
  ga(‘send’, ‘event’, ‘feedback’, ‘providedfeedback-thumbsup’, ‘[feedback text]’ );

**Comment by jmacaluso711** [comment]
@kayiuho @kmahsmith after the user submits feedback on a given page will they not have access tot the feedback widget again?

**Comment by kayiuho** [comment]
I agree. They can come back and comment again later, even if they had submitted something before.

**Comment by jmacaluso711** [comment]
As per Ric discussion..Need to update the event tag to include the URL:
`ga('send', 'event', 'feedback-wasthishelpful', 'clickthumbsdown', [URL]);`
