### ISSUE TITLE
Tracking URLs needed from Rick

### ISSUE THREAD

**Issue by theakatz** [infor-design/website#555]
- URL for when IDS team members send someone the site link via email 
- URL for when Nunzio sends his major email announcement on June 10th 
- others tbd

**Comment by swetteinfor** [comment]
Please refer to https://paper.dropbox.com/doc/UTM-links-for-Design.Infor-Guide-and-Archive-of-Links-fwJy6eM0ylSKdPkKa5MDx for updating which links were used.



Outside of the actual destination URL, there are 3 things to select for sending a link: the source , the medium & the campaign. Let’s assume email will often be the medium, so we only need to focus on source and campaign. 


**source**
  "IDS-newsletter" - the IDS newsletter
  “org-wide-announcement” - nunzs mailers
  “one-off” - anything else that goes to product teams or a larger audience


**campaign**
  - for the newsletter, just try and logically number each issue that goes out and add the date i.e.  issue1-6.25.18
  - for an org wide announcement, just do the best job of labeling it, i.e. prodteamjuneupdate-6.25.18
  - for a one off, just do the best job of labeling


**Example**

This all comes together into something like this: design.infor.com?utm_source=newsletter&utm_medium=email&utm_campaign=issue1
