### ISSUE TITLE
Show sticky table of contents on code docs pages

### ISSUE THREAD

**Issue by nickwynja** [infor-design/website#558]
![screen shot 2018-05-28 at 12 11 36 pm](https://user-images.githubusercontent.com/1012017/40622705-d5b97b74-6270-11e8-827f-0695f03c269f.png)
![screen shot 2018-05-28 at 12 12 21 pm](https://user-images.githubusercontent.com/1012017/40622706-d70d4c26-6270-11e8-9fd8-e88dffe0a4f2.png)

**Comment by kayiuho** [comment]
I'm concerned about having a floating/sticky box/container on top of what we already have "fixed" on the page (left side nav + top nav + "what's your role" button). It could become very distracting with the visual "clutter".

I agree that a super long page, like Data Grid, needs to have a way for users to navigate to sections, I'll look into making this sticky box/container a small element that could expand on click to expose all the links. @jmacaluso711 what do you think? any foreseeing dev problem with that approach??

**Comment by kayiuho** [comment]
Looked into this more and got some real data from Rick which shows 90% of users are on screens larger than 1440px. Once the page goes under 1440, there is pretty much no white space on the right hand side to accommodate anything. 

SO. I mocked up a Dropdown on the upper right corner on XL (and it won't show in L,M,S,XS).

The Dropdown will show H2's from that page only. 
For example, on https://design.infor.com/code/ids-enterprise/latest/datagrid, these are the dropdown selections:

- Data Grid Code Specs
- Code Examples
- Column Settings (Formatter Specific)
- Formatters
- Creating Custom Formatters
- Editors
- Column Settings (Editor Specific)
- Keyboard Shortcuts
- States and Variations
- Responsive Guidelines
- Upgrading from 3.X

![screen shot 2018-06-13 at 3 08 13 pm](https://user-images.githubusercontent.com/34747859/41372546-a3f2223c-6f1b-11e8-9d2e-368fb971d8bf.png)

**Comment by clepore** [comment]
My initial thoughts on the dropdown is that a dropdown isn't normally used too often as a "navigation tool" for inside of a page. I was imagining something more like what [bootstrap does here](http://getbootstrap.com/docs/4.1/getting-started/javascript/) with a small, unobstrusive outline of the page.

**Comment by kayiuho** [comment]
@jmacaluso711 what can you do with this kind of idea?? (mirroring our left nav style)

<img width="1440" alt="screen shot 2018-06-13 at 4 13 36 pm" src="https://user-images.githubusercontent.com/34747859/41375816-2f5b097a-6f25-11e8-864f-434231cbf01c.png">

**Comment by jmacaluso711** [comment]
looks good to me.. I'll attempt to get the active state working 👍

**Comment by clepore** [comment]
I wouldn't spend a lot of time on it unless you want to. I know bootstrap used to have a scrollspy component that would track which `#` you were scrolling to and update.

**Comment by kayiuho** [comment]
@jmacaluso711 
Using same styling as `.ids-list`, EXCEPT font size which is 14px for the links.
Border color same as `.ids-list--heading-accordion` which is 1px solid #d8d8d8.
