### ISSUE TITLE
Steps for Redirecting to design.infor.com

### ISSUE THREAD

**Issue by theakatz** [infor-design/website#561]
1. Static Header for soho.infor.com: 

- [x] design needed for a static banner to live at the top of the soho.infor.com page 
- [x] Rick to provide tracking URL 
- [x] Tim to implement on to soho.infor.com --this is static so should live at the top of the site, on every page, and never go away 

Timing: Will live on soho for the entire month of June 

2. Redirect soho.infor.com to design.infor.com URL 
- [x] Thea to work with IT to redirect soho.infor.com to go directly to design.infor.com 
- [x] Thea to work with IT to rename soho.infor.com to new URL: sohodeprecated.infor.com (without external access like now)
- [x] @kayiuho see https://github.com/infor-design/website/issues/612

Timing: July for the redirect 

Note: We might never deprecate soho.infor.com --but heavily push using design.infor.com instead

**Comment by tmcconechy** [comment]
Ok, in July we can change the DNS. I usually just send this to IT helpdesk.

The problem of: Redirecting / But not redirecting from a specific link. I think is possible but will have to review that with IT. 

If not we can do it in code or with a query parameter or something. But it adds a wrinkle to work through.

**Comment by theakatz** [comment]
Ok, good to know. We will regroup closer to July on it then.

**Comment by swetteinfor** [comment]
**User: sees banner on soho.com**
for each page dimension for indicating the banner is active. 

    ga('set', {
      'dimension10': '[viewingSohoIDSbanner]',
      });

if user is viewing a page without it ( for example, when we stop showing the banner) , the variable should up as blank because we will have the dimension expire on page hit


**user: clicks on the banner…**

     ga('send', 'event', 'internalcampaign', 'click', 'SohoIDSbanner' }


**User: gets redirected from a soho page to IDS**
do nothing. and hope it gets stored in the referring URL

**Comment by kayiuho** [comment]
So on soho.infor.com, we will have both the modal AND the top banner, right? 
- Modal can be dismissed upon arrival.
- Top banner is static and will stay on every page. Q: Do we want a "X" on this banner? or remove it so hopefully it will draw more visitors to design.infor.com?

Thoughts?? @theakatz @clepore @jmacaluso711 @tmcconechy @swetteinfor 

Mocks are here for reference:
<img width="1435" alt="screen shot 2018-06-11 at 3 22 34 pm" src="https://user-images.githubusercontent.com/34747859/41252691-eb25c924-6d8b-11e8-8e49-f5f6d05809ec.png">

<img width="1439" alt="screen shot 2018-06-11 at 3 22 59 pm" src="https://user-images.githubusercontent.com/34747859/41252694-ee2f7c00-6d8b-11e8-9ee3-0fac49a6f5e5.png">

**Comment by theakatz** [comment]
We want the top banner to be there always--I don't think we want a way to get rid of it. 

As it's been implemented, the modal can be dismissed and should only show up once for a user until they either click it or dismiss it. They shouldn't see it more than once....

**Comment by kayiuho** [comment]
Ok, @tmcconechy - here's some specs!

- Banner bg is the status Yellow (#FFD726)
- 30px left and right padding
- 20px top and bottom padding (height should then be 74px)
- Primary Button
- Text and button should wrap on responsive

![screen shot 2018-06-11 at 4 26 13 pm](https://user-images.githubusercontent.com/34747859/41255337-2ee6a9aa-6d94-11e8-89c0-e11d16cd2d9d.png)

**Comment by tmcconechy** [comment]
So add the banner the second time they load the page? Or just remove the popup and add the banner now?

**Comment by theakatz** [comment]
Keep both up at the same time, but remove the modal if they come back to the site and keep the banner at the top forever. 

so:
- new user sees both modal in middle of page and banner at top 
- same user comes back later that week and sees just the banner at top

**Comment by tmcconechy** [comment]
ok the banner is live now on https://soho.infor.com/
when clicked it will report to GA the same dimension as clicking the primary button on the modal

```
ga('send', 'event', 'internalcampaign', 'click', 'SohoIDSAnnouncement' , {'dimension1': 'clickedIDSannouncement'} );
```

**Comment by tmcconechy** [comment]
Not that easily, seems like i would have to customize for each of the different page types rewrite part of the css for each page type for the header sections.

Maybe we consider that overkill?

![screen shot 2018-06-12 at 2 28 26 pm](https://user-images.githubusercontent.com/814283/41309522-fa9d6aa8-6e4c-11e8-8c36-06520cb7291d.png)

**Comment by theakatz** [comment]
hmmm ok. I think we OG discussed having it on every page, but just the home page is probably good enough. Thanks for looking into!

**Comment by clepore** [comment]
I think the homepage will be fine for now. When is the deprecation date for the old site?

**Comment by theakatz** [comment]
we said July we are going to begin to redirect and just link back to soho in the footer. 

@tmcconechy did you use a URL that tracks that they are coming from soho--- @swetteinfor does he need one or will we be able to tell without one?

**Comment by tmcconechy** [comment]
I used the same one as when pressing the primary button on the modal. Figured its the same idea. But @swetteinfor can let me know if he thinks otherwise. Specificall

```
ga('send', 'event', 'internalcampaign', 'click', 'SohoIDSAnnouncement' , {'dimension1': 'clickedIDSannouncement'} );
```

**Comment by kayiuho** [comment]
I think it's okay to have the banner only on the HP of soho.infor.com for now, if implementing on every page isn't worthwhile of our time. Unless later on, we're getting data that there's still a lot of people using soho.infor.com, then we'll take next step.
