### ISSUE TITLE
Link Principles on home page to their page

### ISSUE THREAD

**Issue by theakatz** [infor-design/website#588]
I just tried to find principles and it was harder than it should have been. I think we should link out to them on the home page.

**Comment by kayiuho** [comment]
@jmacaluso711 - can you add a button in between the Design Principles copy and the icons? And link to: https://design.infor.com/guidelines/identity/our-principles

![screen shot 2018-07-09 at 3 48 39 pm](https://user-images.githubusercontent.com/34747859/42472536-9bf5a2ec-838f-11e8-830d-1a5e26c59745.png)

**Comment by jmacaluso711** [comment]
Sure
