### ISSUE TITLE
give feedback submitter a chance to leave their email

### ISSUE THREAD

**Issue by swetteinfor** [infor-design/website#589]
![imagine being this user](https://user-images.githubusercontent.com/20357266/41746952-3e8e4366-757a-11e8-86b1-aa8606886b4e.png)

![example](https://user-images.githubusercontent.com/20357266/41746962-4b8316be-757a-11e8-8aca-8fa493a59583.png)

**Comment by swetteinfor** [comment]
going off nicks question about saving data. you can store their email in the same event. or we can add a new event for the email being saved. once you have the interaction nailed down i can provide the guidance for the

**Comment by jmacaluso711** [comment]
This is being addressed in #590
