### ISSUE TITLE
Build out the feedback feature to show user activity

### ISSUE THREAD

**Issue by swetteinfor** [infor-design/website#590]
i.e.: ![example](https://user-images.githubusercontent.com/20357266/41747009-75b2798e-757a-11e8-8630-4caab7a7c8e1.png)

## Details:
- Looking for something more along the lines of having a count of how many likes and dislikes we are receiving on the thumbs up and thumbs down. We are hoping to show more action as users vote. 
- "0 out of 1 found this helpful, 2 comments" -- maybe show engagement similar to this to help increase engagement

**Comment by theakatz** [comment]
@swetteinfor what do you want here?

**Comment by swetteinfor** [comment]
I think Kaiyu needs to add this ticket (https://github.com/infor-design/website/issues/589) as well, as part of the designing

**Comment by kayiuho** [comment]
I added the count in the mockup. It is above the thumbs up and down because it looks cleaner once the input fields pops up after clicking on the icon.

![screen shot 2018-08-21 at 10 44 46 am](https://user-images.githubusercontent.com/34747859/44408963-70d73c80-a52f-11e8-8ba7-15421c45734c.png)

Also added the optional email (from ticket #590):
![screen shot 2018-08-21 at 10 44 58 am](https://user-images.githubusercontent.com/34747859/44408970-73d22d00-a52f-11e8-8344-5838be873891.png)

If this is good to go, I can zip up the sketch file for you, @jmacaluso711!

**Comment by kayiuho** [comment]
@jmacaluso711 
[IDS_site_feedback_20180821.sketch.zip](https://github.com/infor-design/website/files/2324203/IDS_site_feedback_20180821.sketch.zip)

**Comment by swetteinfor** [comment]
added the email event to the event spec: https://paper.dropbox.com/doc/IDS-Google-Analytics-Specifications--ALWDmH0o6rVY6vb_cXuuEus~Ag-ggGkDJiPNHwz5UHzORCpD


**And then the user also submits his email**
Category: feedback-wasthishelpful
Action: providedemail - thumbsup, providedemail - thumbsdown
Label: [feedback text]
Dimension 9: [email]


    ga(‘send’, ‘event’, ‘feedback-wasthishelpful’, ‘providedemail - thumbsup’, ‘[feedback text]’ {'dimension9': '[email]'} );

**Comment by clepore** [comment]
@jmacaluso711 told me that we'll need to store the count somewhere, but @swetteinfor said we can't use Google Analytics to do this. 

Do we have any other ideas?

If not we'll need to implement our own database storing feature and then provide a way to retrieve the data from said database, which vastly changes the scope of this feature (and would require a discussion).

**Comment by tmcconechy** [comment]
Maybe you could try to use https://firebase.google.com/ we did that before on the golf site and it works well.

**Comment by clepore** [comment]
There is also the [gdocs web api](https://developers.google.com/analytics/devguides/reporting/core/v4/quickstart/web-js)

**Comment by clepore** [comment]
- [x] Email field
- [ ] Saving/retrieving stats

**Comment by nickwynja** [comment]
We also have access to the DB that runs Wagtail. We could add a custom python endpoint which stores and receives this information. That would require Artem's time, mostly, unless John wants to dig more into the python API stuff.
