### ISSUE TITLE
Weird truncation in blog posts home page

### ISSUE THREAD

**Issue by swetteinfor** [infor-design/website#607]
https://design.infor.com/blog

![screen shot 2018-06-29 at 10 45 17 am](https://user-images.githubusercontent.com/20357266/42106377-dc1b0790-7ba1-11e8-9f9d-82bb614e60cf.png)

Details:
Content needs to be added into one section of the CMS so that the truncation is fixed.

**Comment by theakatz** [comment]
note: couldn't figure out how to place the images into the text area, can't make this update until I figure out how to do that

**Comment by theakatz** [comment]
dependent on #606

**Comment by nickwynja** [comment]
Enh, nevermind. I just did it in the view. :/
