### ISSUE TITLE
Step Process Page Wont Load

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/website#622]
**Describe the bug**

Went to look at step process docs and it did not load. 

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/stepprocess
1. or click step process in the submenu from https://design.infor.com/code/ids-enterprise/latest
1. See error

**Expected behavior**

**Platform**
 Any

**Additional context**

This may be because of its placement in enterprise, willing to work through it with someone but just noting for now.

**Comment by jmacaluso711** [comment]
It appears that there are no docs for step process which is causing the 404

`https://design.infor.com/api/docs/ids-enterprise/latest/docs/stepprocess.json`

**Comment by clepore** [comment]
I thought I fixed this in the latest deploysfor 4.9.x. There was a PR for it last week.

**Comment by tmcconechy** [comment]
https://github.com/infor-design/enterprise/pull/562 should have removed that from the site.

**Comment by clepore** [comment]
Yeah I forgot to close this is all.
