### ISSUE TITLE
Some sample pages using sample data api wont load 

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/website#628]
**Describe the bug**

Pages that load api data are giving an error. Not sure if where this fix would go yet so putting it here.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/datagrid/example-grouping.html?font=source-sans
2. Look in the console and observe error

Failed to load https://latest-enterprise.demo.design.infor.com/api/accounts: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://design.infor.com' is therefore not allowed access.

**Expected behavior**
No error

**Additional context**
[Noted on Ms Teams](https://teams.microsoft.com/l/message/19:2b0c9ce520b0481a9ce115f0ca4a326f@thread.skype/1536051602386?tenantId=457d5685-0467-4d05-b23b-8f817adda47c&groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&parentMessageId=1536051602386&teamName=IDS%20Enterprise%20Development%20(SoHo%20Xi)&channelName=General&createdTime=1536051602386)

The problem seems to be the basepath is incorrect on this site due to a redirect...
```
var url = '{{basepath}}api/accounts';
```

I wonder if we can now use relative links as the reason for the basepath was the way the old site was setup.

**Comment by clepore** [comment]
A team member noticed two more examples that do not work:
- [latest/demo/datagrid/example-index](https://design.infor.com/code/ids-enterprise/latest/demo/datagrid/example-index?font=source-sans)
- [latest/demo/datagrid/example-row-reorder](https://design.infor.com/code/ids-enterprise/latest/demo/datagrid/example-row-reorder.html?font=source-sans)

**Comment by tmcconechy** [comment]
This seems to be fixed now. Good work @EdwardCoyle.
Closing
