### ISSUE TITLE
Add optional email field to page feedback comment

### ISSUE THREAD

**Issue by nickwynja** [infor-design/website#629]
**Is your feature request related to a problem? Please describe.**
The feedback we're getting through the page's 👍 👎 are helpful but there's no mechanism for us to know who left the feedback and how to follow up with them if we have questions, to clarify, or provide answers.

**Describe the solution you'd like**
To get the person's email address if they choose to fill out the email field so that we can follow up.

**Comment by nickwynja** [comment]
@swetteinfor To accomplish this, do we need to add any additional fields on the GA side? Or can we just start including the `email` field in the current POST?

**Comment by nickwynja** [comment]
Duplicate of #589.

**Comment by swetteinfor** [comment]
ah, sorry nick i didn't see this thread. good thinking here ;)
