### ISSUE TITLE
Make sure all relativeUrls start with the library

### ISSUE THREAD

**Issue by jmacaluso711** [infor-design/website#630]
**Describe the bug**
Saw an issue where some of the docs results are returning `relativeUrl` without the library.

**To Reproduce**
1. Index the docs with `make index_s3`
2. Go to website search page and search
3. I tested "translations"
4. You'll see some of the results are missing the library in the `relativeUrl`

**Expected behavior**
**Wrong**
`relativeUrl: 4.8.0-dev/translations`

**Correct**
`relativeUrl: ids-enterprise/4.8.0-dev/translations`

**Comment by nickwynja** [comment]
Actually, this was a case of bad data. There were some leftover files in S3 which at the time were uploaded without the library. I cleared those out yesterday in attempt to fix some of the other issues.

@jmacaluso711 Can you re-index and see if this issue has gone away?

**Comment by corpulent** [comment]
@jmacaluso711 `curl -X DELETE "localhost:9200/INDEX_NAME"`

**Comment by jmacaluso711** [comment]
Yep, looks good now. thanks
