### ISSUE TITLE
Cert Expired Today

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/website#633]
**Describe the bug**

*.demo.design.infor.com site indicates that the cert is expired today.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/input/example-index?font=source-sans
2. Notice that the pages do not load...
3. Look in the console: "Failed to load resource: net::ERR_CERT_DATE_INVALID"

**Platform**
All

@nickwynja @clepore

**Comment by nickwynja** [comment]
@tmcconechy Thanks for catching this. @corpulent will be able to fix. We finally worked out the automated renewal of these certs, we just didn't think to renew these boxes.

**Comment by tmcconechy** [comment]
In case needed. This is what a windows user reported on MS Teams.

![screen shot 2018-08-21 at 8 46 51 am](https://user-images.githubusercontent.com/814283/44402135-ce16c200-a51e-11e8-9450-0a465da2f3b4.png)

**Comment by clepore** [comment]
@artem is this also on a cron just like design.infor.com?

**Comment by clepore** [comment]
This is fixed for now, but will need a more permanent "auto" fix going forward.
