### ISSUE TITLE
MVP Search: Results Tweaking

### ISSUE THREAD

**Issue by clepore** [infor-design/website#642]
**Is your feature request related to a problem? Please describe.**
We need define how we want to logically handle tweaking the results, such as
- deduping results
- weighting stuff higher than others

**Describe the solution you'd like**
- [ ] Come up with a document of rules
- [ ]  Hand off for implementation
- [ ] Test and itereate

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by nickwynja** [comment]
### Docs Indexing Script

Fields to add:
* library
* version
* title
* description

**Comment by nickwynja** [comment]
Instead of combining the two indexes from elasticsearch and wagtail, we should use ES's standard combined index search, like this:

http://localhost:9200/dev__docs,dev__wagtailcore_page/_search?size=100&q=buttons

**Comment by nickwynja** [comment]
* title
* uri
* design / code section
   * library
   * version
* description / highlight

**Comment by nickwynja** [comment]
The plan here is to use the result coming from searching across both `dev__docs,dev__wagtailcore_page` indexes and loop through the result to get the necessary above information from either the internal wagtail python API or from what has been indexed.

**Comment by nickwynja** [comment]
I think once we figure out a solution for deduping versions we can release and leave further refinements for a future issue.
