### ISSUE TITLE
MVP Search: Design Audit/Tweaks

### ISSUE THREAD

**Issue by clepore** [infor-design/website#643]
**Is your feature request related to a problem? Please describe.**
As we near finishing search, we should probably give it one final design pass.

**Describe the solution you'd like**
- Audit the search/search results and create a list of design changes/tweaks
- Handoff to development for implementation

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by jmacaluso711** [comment]
@kayiuho Here are some screenshots of the current implementation of search

![2104ab11-c975-4d74-bf88-167c333e11c1](https://user-images.githubusercontent.com/1084735/45182123-6f279d00-b1ee-11e8-8daf-d9e8e7937042.png)

![e01a9016-e383-49ab-8ddb-5a447e907105](https://user-images.githubusercontent.com/1084735/45182135-777fd800-b1ee-11e8-87c3-a6bf0739730b.png)

![8c4ce97d-1403-4c7e-9957-a3beaa97b32e](https://user-images.githubusercontent.com/1084735/45182142-7b135f00-b1ee-11e8-9b79-d87abd4c6a7d.png)

**Comment by jmacaluso711** [comment]
what about putting the version in the title?

![screen shot 2018-09-07 at 11 41 28 am](https://user-images.githubusercontent.com/1084735/45229114-03e3d680-b293-11e8-8e43-76110ebc7673.png)

**Comment by kayiuho** [comment]
I think it still needs to have the word "Version" in it to give more context (for especially non-developers).

**Comment by kayiuho** [comment]
I was thinking.. 

Charts • Version 4.6.0
**Found In:** ids-enterprise version 4.6.0
Page description lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ac pellentesque mi, vel malesuada mauris.

I don't love that it's displaying repeated info, I think having an url is more clear, like **Found In:** https://design.infor.com/code/ids-enterprise/4.7.0/charts

**Comment by nickwynja** [comment]
I like showing the URL as well. Makes it feel very familiar to Google. A couple features I think we should add:

- [ ] A "Search" primary button; enter should submit the result but a button should also show to give people the option if they don't know to press enter
- [ ] When a search is submitted, the query should be displayed in the url, like `/search?q={query}` so that browser history is maintained as well as the option to share links to search results
- [ ] In addition to above, when a page is loaded like `/search?q={query}` the app should get the search query parameter and load the page with that search result

**Comment by nickwynja** [comment]
- [ ] Show only 2 lines of `highlight` preview
- [ ] Get latest version of `ids-enterprise,ids-css, ids-pendo` from service and dynamically add to search request

**Comment by nickwynja** [comment]
@jmacaluso711 A couple other small things here:

- [ ] If possible, update URL to be `/search` not `/site/search`
- [ ] Clean up how title displays on search pages to remove query string. If necessary, I'd rather just remove the query string completely but ideally it would be something like `Search / {{Query}} - Infor Design System`


![image](https://user-images.githubusercontent.com/1012017/45647854-f13c7f00-ba94-11e8-9a23-36210670002b.png)
