### ISSUE TITLE
404 error on the locale page

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/website#649]
**Describe the bug**
There is a 404 error on the locale page.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/locale
2. Scroll to the Currently Supported Locales section
3. Click the link (it 404s)

**Comment by nickwynja** [comment]
@tmcconechy Where should this link to?

**Comment by tmcconechy** [comment]
https://github.com/infor-design/enterprise/pull/776 Not sure why I can’t get “Closes” to work?
