### ISSUE TITLE
Change log shows 4.9 version (not 4.10)

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/website#650]
**Describe the bug**

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/index
2. Click on the link at the bottom to release notes that directs to https://design.infor.com/code/ids-enterprise/latest/changelog

Notice that the page is showing 4.9 change log. Also the changing of versions doesnt work with the switcher.

**Expected behavior**
https://design.infor.com/code/ids-enterprise/latest/changelog should show current version of the change log.

**Additional context**
Reported on MS Teams

**Comment by clepore** [comment]
We saw this before where for some reason our code or plugin isn't recognizing semver `4.10.0` as a good semver. We need to investigate why because `4.10.0` is a valide semver.
