### ISSUE TITLE
Change the way the website consumes/displays tokens per version

### ISSUE THREAD

**Issue by clepore** [infor-design/website#672]
**Is your feature request related to a problem? Please describe.**
Since we changed to tokens 2.0, we need to update the website to handle the new structure and files that are POSTed with the documentation from each code repo.

**Describe the solution you'd like**
Update the code to handle the new structure (and maybe the old too? maybe not). Also note we do not use `.raw.json`, its just `.json` now.

**Describe alternatives you've considered**
n/a

**Additional context**

Pre-req:
- https://github.com/infor-design/css/issues/176
- https://github.com/infor-design/enterprise/issues/951

**Comment by nickwynja** [comment]
I think what we need to do here is:

- In a `docs-content-page`, pass the `library` into the `<tokens-table>`
    - In some preliminary experimentation here, `library` isn't always set. We need to take a look at why
- `getTokenData()` in `token.service` can fetch the tokens from the specified `library`
    - If getting the tokens from a library, the current expected path is that the token file would live at: `/api/docs/ids-{{library}}/latest/ids-identity/theme-soho.json`
- Have `getTokenData()` in `token.service` default `library = ids-identity` so that for the design docs, we just don't pass in a `library` and it'll default to getting the tokens from `ids-identity/latest`. If this is the case, the tokens would be at: `/api/docs/ids-identity/latest/tokens/web/theme-soho.json`


There is no suitable way to maintain backwards compatibility of the tokens table with the previous setup of tokens so in cases like previous versions of CSS that show the table, we could just hide the table if the `tokens.service` fails to find the new token file it's expecting.

**Comment by clepore** [comment]
I can make a simple JSON file to work with, versus the crazy nested hierarchy as seen below:
```
"active": {
          "background": {
            "value": "#2578a9",
            "component": "buttons",
            "deprecated": "button-primary-active-bg-color",
            "original": {
              "value": "{color.brand.primary.alt.value}",
              "component": "buttons",
              "deprecated": "button-primary-active-bg-color"
            },
            "name": "button-color-primary-active-background",
            "attributes": {
              "category": "button",
              "type": "color",
              "item": "primary",
              "subitem": "active",
              "state": "background"
            },
            "path": [
              "button",
              "color",
              "primary",
              "active",
              "background"
            ]
          }
        },
```

@jmacaluso711 Let me know if there are any properties here that you might want/need to make parsing them easier. 

Right now this is what I have:
```
[{
  "name": "button-color-primary-base-icon",
  "value": "#ffffff",
  "category": "button",
  "original": {
    "value": "{button.color.primary.base.font.value}"
  }
},
...
]

**Comment by nickwynja** [comment]
@clepore Can you update to add a list of name variations/options so that we can either list the names for different formats or provide an option to select whether you'd like to see "SASS" vs. "JS"?

**Comment by clepore** [comment]
As such:
```
[{
  "name": {
        "sass": "button-color-primary-base-icon",
        "javascript": "button.color.primary.base.icon"
    },
  "value": "#ffffff",
  "category": "button",
  "original": {
    "value": "{button.color.primary.base.font.value}"
  }
}]```

**Comment by jmacaluso711** [comment]
Is it possible to also add the `type` like so:

```
[{
  "name": {
        "sass": "button-color-primary-base-icon",
        "javascript": "button.color.primary.base.icon"
    },
  "value": "#ffffff",
  "category": "button",
  "type": "color"
  "original": {
    "value": "{button.color.primary.base.font.value}"
  }
}]
```

**Comment by jmacaluso711** [comment]
I think we added `tokensCategory` to the docs api a while back so that we could pass it to the tokens table. They were named plural, but now the tokens are singular. Should we ditch the `tokensCategory` and take the category from the route or fix it so they are singular?

Docs API:
```
body: "<p>To create a plain list, use <code>.ids-list</code>."
demo: {path: "/ids-list/index.html"}
description: "Some text about using ids-list."
title: "Lists"
tokensCategory: "lists"
```

Tokens:
```
body: (3) [{…}, {…}, {…}]
breakpoint: (5) [{…}, {…}, {…}, {…}, {…}]
button: (41) [{…}, {…}, {…}, {…}, {…}, {…},...
checkbox: (20) [{…}, {…}, {…}, {…}, {…}, ...
color: (97) [{…}, {…},
list: (97) [{…}, {…},
...
```
