### ISSUE TITLE
Https Redirect not working on all demo sites

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/website#697]
**Describe the bug**
Some demo sites redirect to https when going to the http version, but some dont.

http://4100-enterprise.demo.design.infor.com/components/datagrid/example-paging-indeterminate-landmark.html - doesnt do it

https//design.infor.com/code/ids-enterprise/latest/demo/button/example-index?font=source-sans&nofrills=true  - does do it fine

Check other demo site combos.

**To Reproduce**
1. Go to any demo site http://4100-enterprise.demo.design.infor.com/components/datagrid/example-paging-indeterminate-landmark.html
2. Should redirect to its https counter part

**Expected behavior**
Should redirect to its https counter part

**Additional context**

One reason this is noticeable is chrome now shows this in a more obvious manner.

![screen shot 2018-11-06 at 4 54 48 pm](https://user-images.githubusercontent.com/814283/48096239-b0373000-e1e4-11e8-827c-b3a5da92f2ca.png)

**Comment by nickwynja** [comment]
I think this might actually be redirecting properly but the `4100-enterprise` container doesn't actually exist now after the outage. `4100-enterprise` on HTTPS currently points to the latest version, I believe.

![image](https://user-images.githubusercontent.com/1012017/48147117-86cde100-e284-11e8-8204-1a7ad8f17554.png)

Still looking into this.

**Comment by nickwynja** [comment]
This has been solved by redeploying the containers.
