### ISSUE TITLE
Iframe external links have `nofrills` in the url

### ISSUE THREAD

**Issue by clepore** [infor-design/website#708]
**Describe the bug**
All external urls should link to an example with the "frills" (aka header)

**To Reproduce**
1. Go to <https://design.infor.com/code/ids-enterprise/latest/input>
2. Click on the "external link" icon to the top right of the iframed example.
3. Notice in the new tab/window, there is no header due to the `nofrills` url query parameter.

**Expected behavior**
There should be a header, as the iframe is the only thing that shouldn't have a header.

**Screenshots**
<img width="918" alt="screen shot 2018-11-20 at 12 51 58 pm" src="https://user-images.githubusercontent.com/742319/48793435-ee445180-ecc4-11e8-8e4a-f038638c19c0.png">

**Platform**
 - all

**Additional context**
n/a

**Comment by nickwynja** [comment]
Just need to change this:

https://github.com/infor-design/website/blob/9d67b00b3997252b9439c5cca5b290deb72142f9/src/web/src/app/components/docs-content-page/docs-content-page.component.ts#L118-L122

So it's:
```js
page.url = this.createDemoUrl(page.slug, true);
```

**Comment by clepore** [comment]
I don't think we want all the examples to lack a header, otherwise they can't view them in different themes. I changed the iframe property to be the only one with the `nofrills` url param in the above PR.
