### ISSUE TITLE
Upgrade from Angular 5.0 to 7.2

### ISSUE THREAD

**Issue by clepore** [infor-design/website#722]
**Is your feature request related to a problem? Please describe.**
In order to gain the ability to use ID/anchor navigation and routing, we would need to upgrade to angular `7.x`

**Describe the solution you'd like**
Upgrade from `ng@5.0` to `ng@7.2` https://update.angular.io/

**Describe alternatives you've considered**
Build our own solution to handle query params or hash routing.

**Additional context**
Source of solution: [stackoverflow/using-anchor-link-id-in-angular-6](https://stackoverflow.com/questions/50836497/using-anchor-link-id-in-angular-6)

**Comment by tmcconechy** [comment]
7.2 is the latest - https://github.com/angular/angular/releases
(just a thought)

**Comment by clepore** [comment]
Per @jmacaluso711 
> ng 6 requires webpack@4.x.. and we’re using `extract-text-webpack-plugin` which is deprecated after webpack@3.x
>
> this seems to be the root of the current error im getting https://github.com/infor-design/website/blob/update-to-ng-6/src/web/config/webpack.common.js#L21
>
>so i guess our options are try to make the build process jive with the latest angular/cli or use an old version of the cli and try to keep the build process as is

**Comment by clepore** [comment]
Looks like we'd have to replace this:
```js
const { NamedLazyChunksWebpackPlugin, BaseHrefWebpackPlugin, SuppressExtractedTextChunksWebpackPlugin } = require('@angular/cli/plugins/webpack');
```
Which was originally [this](https://github.com/infor-design/website/commit/a9d5ec9ac89e3954dd74d4d8fb88d003f9b78926):
```js
const { NamedLazyChunksWebpackPlugin, BaseHrefWebpackPlugin } = require('@angular/cli/plugins/webpack');
```
...which is what `ng eject` gave us and the angular documentation doesn't have a clue as to what they should change to.

**Comment by theakatz** [comment]
John to test this with current designs. Design to provide working design files by 2/5.
