### ISSUE TITLE
Add GDPR cookie notice

### ISSUE THREAD

**Issue by nickwynja** [infor-design/website#723]
See scripts in [_generic-cookie-banner-package.zip](https://github.com/infor-design/website/files/2880432/_generic-cookie-banner-package.zip) sent to us from Infor web team. (Seems to be using https://github.com/dobarkod/cookie-banner/)

Required text is:

>This website uses functional cookies, which enable the website to provide an enhanced user experience and personalization. They may be set by us or by third party providers whose services we have added to our pages. By continuing to use this site, you accept the use of functional cookies. You can modify your cookie settings through the preferences setting of your browser. If you choose not to allow these cookies, some or all of the website content may not function properly.

I think we could probably customize the design if we want but let's get it integrated first.

See http://www.inforcustomeradvisoryboard.com/ for example.

**Comment by jmacaluso711** [comment]
added to https://github.com/infor-design/website/tree/724-ui-changes
