### ISSUE TITLE
Website UI/UX Changes

### ISSUE THREAD

**Issue by clepore** [infor-design/website#724]
**Is your feature request related to a problem? Please describe.**
Build new designs for certain pages.

**Describe the solution you'd like**
Changes include:
- [ ] homepage design
- [x] SideNav accordion styles
- [x] Icon asset pages #712 
- [ ] Demo theme switcher / navigation (depends on https://github.com/infor-design/css/issues/194)
- [x] Right side page index (quick links) responsive behavior
- [x] Right side page index scroll spy (active states)
- [x] back to top button (not sure how set in stone this is but @beccakroll thinks it's nice)
- [x] updated header design
- [x] updated footer design

(Design assets will be added to the issue as they are finished)

**Describe alternatives you've considered**
n/a

**Additional context**
- Analyst Summit is happening *3/15/19* (deadline)

**Comment by nickwynja** [comment]
@jmacaluso711 Designs for the sidebar and code landing pages will be uploaded shortly. For the sidebar, you'll need to update `ids-list` in `ids-css` repo and then do the whole `npm link` dance. For now, just take `npm i ids-identity@latest` and we can push updates to tokens as necessary for these design updates.

**Comment by kentonquatman** [comment]
Attaching the Sketch file for some of the interior pages.
[IDS_Components_20190212.zip](https://github.com/infor-design/website/files/2857472/IDS_Components_20190212.zip)

**Comment by nickwynja** [comment]
@jmacaluso711 Let me or @kentonquatman know if you need anything else like states for any of those page designs.

**Comment by nickwynja** [comment]
@kentonquatman Can you add a state for global menu when it's open on mobile? This is the current:

![image](https://user-images.githubusercontent.com/1012017/52819926-9bd2c100-3078-11e9-87bc-2a2aa3554e4e.png)

**Comment by nickwynja** [comment]
Following the menu updates, I think we should review and refine the updates so far and then break out the homepage and theme work into separate tickets.
