### ISSUE TITLE
Please send me the icon [...]

### ISSUE THREAD

**Issue by asampogna** [infor-design/website#725]
Hello, I hope that you are well, could you send me the SVG file for the icon "..." please?
![picture1](https://user-images.githubusercontent.com/47124792/52075057-efa9ba00-2550-11e9-81b6-2e3a67acb818.png)

Appreciate it...
Kind regards!

**Comment by nickwynja** [comment]
Duplicate of https://github.com/infor-design/design-system/issues/268
