### ISSUE TITLE
Website Home Page Redesign

### ISSUE THREAD

**Issue by theakatz** [infor-design/website#739]
**Is your feature request related to a problem? Please describe.**
Build new designs for certain pages.

**Describe the solution you'd like**
Changes include:

* [x]  homepage design
* [x] Main side bar nav responsive behavior

**Comment by kentonquatman** [comment]
Latest designs for the IDS homepage.
[IDS_Home_20190301.sketch.zip](https://github.com/infor-design/website/files/2920123/IDS_Home_20190301.sketch.zip)

**Comment by nickwynja** [comment]
Outstanding design/development homepage updates:

- [ ] Adding mention of "principles" in hero link or heading
- [ ] Adding heading TDB to primary copy block under hero
- [ ] Replace Design Tokens image placeholder
- [ ] Section Eyebrow copy TBD or removed?
