### ISSUE TITLE
Improve performance of Docs API server

### ISSUE THREAD

**Issue by nickwynja** [infor-design/website#748]
**Is your feature request related to a problem? Please describe.**
Requests to endpoints like `/api/docs/ids-identity/latest/theme-soho/icons/standard/metadata.json` often take 2s "Waiting (TTFB)", no matter which environment.

**Describe the solution you'd like**
Content loading within 100-200ms.

**Describe alternatives you've considered**

**Additional context**

**Comment by clepore** [comment]
- [x] Review the method of retrieving documentation versions from AWS
- [x] Utilize django models for versions if we can
- [ ] Update API to access the versions
- [ ] Have the website switch to using that API call

**Comment by clepore** [comment]
Also noting that this performance will drastically help https://github.com/infor-design/website/issues/751.

**Comment by nickwynja** [comment]
Currently seeing this issue when there are no versions defined for a library:

```
File "./docs/aws.py" in get
  192.             latest_version = semver.rsort(active_lib_semvers, True)[0]

Exception Type: IndexError at /api/docs/ids-identity/latest/tokens/web/theme-soho.simple.json
Exception Value: list index out of range
```

We should check the `if active_lib_semvers is not Empty` first and return `404` if no versions exist, rather than an error.
