### ISSUE TITLE
"View code on Github" links are not working on Tree component documentation

### ISSUE THREAD

**Issue by csachetti** [infor-design/website#751]
https://design.infor.com/code/ids-enterprise/latest/tree

**Comment by nickwynja** [comment]
Hi @csachetti, thanks for the report. I'm able to recreate the problem. It has to do with a timing issue, so the links will sometimes work but not always. We're on it!

**Comment by nickwynja** [comment]
In the meantime, you can use the direct link for the version and it should work every time:

https://design.infor.com/code/ids-enterprise/4.15.0/tree

**Comment by nickwynja** [comment]
@csachetti This is working properly now. Thanks again for the report!
