### ISSUE TITLE
Homepage Design QA

### ISSUE THREAD

**Issue by kentonquatman** [infor-design/website#753]
I've attached a ZIP file with comments on the new IDS homepage and the latest comps for reference.
[IDS_Homepage_QA_20190308.zip](https://github.com/infor-design/website/files/2947513/IDS_Homepage_QA_20190308.zip)

**Comment by nickwynja** [comment]
Related to #739.

**Comment by nickwynja** [comment]
@jmacaluso711 Can you please update the homepage with the following copy? 

[IDS_Content_Website_and_Communications.pdf](https://github.com/infor-design/website/files/2957562/IDS_Content_Website_and_Communications.pdf)
