### ISSUE TITLE
Update IDS Blog design

### ISSUE THREAD

**Issue by nickwynja** [infor-design/website#772]
**Is your feature request related to a problem? Please describe.**
The blog design probably needs redesigned to match all of the other things we've redesigned.

**Describe the solution you'd like**
Update blog design.

**Describe alternatives you've considered**
Not updating the blog design.

**Additional context**
n/a

**Comment by nickwynja** [comment]
See designs here: https://inforus.invisionapp.com/share/4DQYRIB6UVT

**Comment by nickwynja** [comment]
@kentonquatman This is ready for review on staging. Can you take a look? I’ve let Gaetano know that we’re going to need hero graphics for each of the posts. I just added random ones for now.

https://staging.design.infor.com/ (ribbon at the bottom of the homepage)
https://staging.design.infor.com/blog (edited)

**Comment by clepore** [comment]
@kentonquatman Just a bump ^^ 👍

**Comment by nickwynja** [comment]
I'm going to proceed with deploying this. Any further feedback can be handled in a future update.

**Comment by kentonquatman** [comment]
@jmacaluso711 and I have a review scheduled for today. There are a handful of things that we'll need to fix, but it shouldn't require a ton of work.

**Comment by clepore** [comment]
Ok - Please (one of you) create an issue with what needs updated post-meeting so we have it logged 👍

**Comment by nickwynja** [comment]
OK - We have some draft blog posts we need to start getting into the CMS which requires this code, so we'll address any of those fixes as we can.
