### ISSUE TITLE
404 on link to initialize

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/website#789]
**Describe the bug**
Navigating to the initialize page will throw a 404 error.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest
2. Click on 'initialize' in the side menu (under utilities)
3. See error

**Expected behavior**
Should get to this doc page (generated) https://github.com/infor-design/enterprise/blob/master/src/behaviors/initialize/readme.md

**Platform**
- Browser Name [chrome]

**Additional context**
Posted on Ms Teams

**Comment by nickwynja** [comment]
Duplicate of https://github.com/infor-design/website/issues/789
