### ISSUE TITLE
Source code example links are 404ing

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/website#794]
**Describe the bug**
Seeing a 404 on some source code links.

**To Reproduce**
1. Click here to go to https://design.infor.com/code/ids-enterprise/latest/accordion
1. Hover over any :octocat: source code icon link
    - It should not have "latest" in the url or it will 404  ❌

It seems like this is intermittent, as refreshes will eventually show it has the correct version in the url.

**Expected behavior**
All of the links should load properly.

**Additional context**
Reported in teams

**Comment by clepore** [comment]
The issues seems to be that the current links when on "latest" are going to url:
```
https://github.com/infor-design/enterprise/blob/LATEST/app/views/components/listview/example-paging-clientside.html
```
Where as they should be going to
```
https://github.com/infor-design/enterprise/blob/MASTER/app/views/components/listview/example-alternate-row-color.html
```

**Comment by nickwynja** [comment]
They shouldn't be going to `master` but the latest semver that the site gathers from the "Library Versions" in the CMS.
