### ISSUE TITLE
Bad link to sohodeprecate

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/website#825]
**Describe the bug**

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/tabs
2. Scroll to the bottom 
3. Click on SoHo Xi Site

**Expected behavior**
This is an old 4.x deprecated version of design.infor.com so there is nothing to point to. So we could either change this to "Soho 10x" https://soho10x.infor.com/ or remove. Developers choice :)

**Comment by tmcconechy** [comment]
@jmacaluso711 - do you know where this link lives in the code?

**Comment by jmacaluso711** [comment]
@tmcconechy Yeah that link is just hardcoded in the footer
