### ISSUE TITLE
Add new meta and OG Image

### ISSUE THREAD

**Issue by jmacaluso711** [infor-design/website#843]
**Is your feature request related to a problem? Please describe.**
Add new meta description and open graph image

**Homepage:**
 

- Please remove the entire Principles carousel.
- The following module that says “Infor Design System” (all copy) will now lead the homepage. Please make these copy updates:
    - Headline: Infor Design
    - Subhead: Use these guidelines and resources to create meaningful experiences for Infor’s products, brand, and customers.
    - Button: Get Started

 
**Metadata:**
 

- Please update the metadata copy:
    - Headline: Infor Design
    - Subhead: Guidelines and resources to create meaningful experiences for Infor’s products, brand, and customers.
- Please update the metadata image to the attached, per Nunzio. If there are image sizing restrictions, please reach out to Danielle for assistance.

![Picture1](https://user-images.githubusercontent.com/1084735/74843532-0eb0f080-52fa-11ea-9037-18999677c4ae.png)

**Comment by jmacaluso711** [comment]
@danirosefishinfor Can we get an image with a square aspect ratio (1200x1200) or a smaller landscape size (1200x630)?

**Comment by danirosefishinfor** [comment]
@jmacaluso711 Here you go!
![IDS meta image Copy](https://user-images.githubusercontent.com/35697768/74844904-2e491880-52fc-11ea-9e33-2f0ff5d10dd8.jpg)
![IDS meta image Copy@1x](https://user-images.githubusercontent.com/35697768/74844905-2e491880-52fc-11ea-95aa-7b0c27eddcfc.png)
![IDS meta image](https://user-images.githubusercontent.com/35697768/74844906-2e491880-52fc-11ea-8dc7-46332dfcf2fc.jpg)
![IDS meta image@1x](https://user-images.githubusercontent.com/35697768/74844907-2e491880-52fc-11ea-92a7-dbf5495e97bb.png)
